### DISCUSSION TITLE
List software on HGVS Nomenclature pages

### DISCUSSION THREAD

**Discussion by reece** [HGVSnomenclature/hgvs-nomenclature#56] [HGVS presentation]
A list of tools that manipulate HGVS expressions would be helpful for the community. This discussion thread is a proposal for how to do so.

- *Scope*: Any software that *manipulates* *general* HGVS expressions may be listed. Here, "manipulates" means that the software must do one or more of the following: 1) parse, 2) generate, 3) validate, or 4) project or translate, and "general" means that the software must perform these operations on a significant subset of variants across transcripts and variant types (insertions, deletions, etc). 
- *Non-endorsement*: Until there is a compliance suite, we should not endorse any tools. Tools may not state or imply an endorsement by HVNC.
- *Order*: Tools will be listed alphabetically, within prescribed categories (TBD). If a tool fits into two categories, it will be listed twice.
- *Format*: All tools will use a similar format for their listing. A template will be provided and used for submissions.
- *Submissions*: Tool developers will submit a pull request for the proposed blurb using a template provided by HVNC. Tools that meet the above rules will be listed.

## Proposed template

**Name**: Template
**Categories**: "GUI" (browser or local), "programming library" (w/language), "web service"
**License**: "Commercial", or name the OS license
**Home page**: https://example.com/
**Description**: The template package provides a browser interface and API for ...

## Implementation

The easiest implementation is to collect blocks of text in single page. Alternatively, it's possible that we could use mkdocs-blogging-plugin to create one page per tool, then use tags to group packages.

**Comment by reece** [comment]
@jfjlaros @ifokkema @Peter-J-Freeman : As tool developers, what other information would you want to include in the template?

**Reply by jfjlaros** [reply]
Some tools that deal with general HGVS expressions are built on top of a set of programming libraries that handle more specialised problems, e.g., [[1](https://github.com/mutalyzer/hgvs-parser), [2](https://github.com/mutalyzer/description-extractor), [3](https://github.com/mutalyzer/crossmapper)]. Should these libraries be described separately?

**Reply by Peter-J-Freeman** [reply]
My feeling would be to keep this a simple list of tools that we endorse as "high quality solutions" which we are effectively endorsing. Most HGVS users are not informaticians, so lets not under estimate the value of the interfaces our tools provide. we could perhaps separate out general tools and informatics tools into 2 sections though?

**Reply by ifokkema** [reply]
I agree that most users reading the list will likely look for graphical interfaces or APIs and not libraries to include in their own code. However, a separate section may be provided for those who are looking for libraries. Optionally, "inheritance" may be provided; e.g., Variant Validator using a modified version of the `hgvs` Python tool, or the LOVD HGVS syntax validation interface/API using the LOVD HGVS libraries.

**Comment by Peter-J-Freeman** [comment]
On reflection, I think that this is a very important resource for all our tools. A concise comprehensive list of the features of the tools would be very helpful to users.  

Things I would like to see mentioned are
- Is there a hosted user-friendly interface?
- API (hosted and for local install and the install options - Useful for clinical labs behind fire-walls)?
- Access to support?
- What tools each platform has
- Input and output formats and whether there is mapping between formats / reference sequences etc.
- How to request features and report bugs
- Future developments expected (which we can of course add to the above sections as they are checked off)

It looks like we will not necessarily be endorsing tools at this stage, but this is something that users could find beneficial in the future. Perhaps we need some comments about this. Perhaps also think of some sort of badging and information to other tools which may wish to be considered in the future (and the Compliance Suite), for example, VEP may want to be considered but currently their HGVS isn't necessarily good enough, but we should aim to provide guidance to improve widely used tools rather than looking to exclude.

**Comment by ifokkema** [comment]
I believe the information most readers will be looking for is what the tools actually do. We can relatively easily categorize this, I believe. Likely, everybody knows well what features of their tools are important to users, although we'll run the risk of having perhaps too many categories in the end.
A quick mockup:
- Validation:
  - Validation of variant descriptions (syntax only)
  - Sequence-level validation of variant descriptions
- Mapping/Lift-over:
  - Mapping between genomic and transcript-based variant descriptions
  - Lift-over between different genomic variant descriptions
- Prediction:
  - RNA-level variant prediction from DNA input
  - Protein-level variant prediction from DNA input
  - Protein-level variant prediction from RNA input
  - DNA-level variant prediction from protein input
- Generating HGVS nomenclature from other input
- Input:
  - HGVS variant descriptions
    - DNA
      - Supports uncertain boundaries
      - Supports repeat syntax
      - Supports methylation changes
      - Supports ...
    - RNA
    - Protein
  - VCF file input
  - SPDI
  - VRS

These features could be listed as text, indicated with short codes, marked in a table format, etc.

**Reply by Peter-J-Freeman** [reply]
Agreed. The issue is that I kind of have 2 tools so not sure whether to put into 2 pages or one. If one page, this is the ideal level of granularity for example, but may be too clunky. This was discussed with @reece and it is a little too deep at the moment, but does provide some ideas for a v2. We need to think what comes out and how to link user documentation. 

```yaml
name: VariantValidator
primary_url: https://variantvalidator.org/
source:
  type: github
  repo_slug: openvar/variantvalidator
types:
- web api
- web user interface
- python libraries
- docker builds
functionality:
- conversion
- normalization
- parsing
- projection
- translation
- validation
- liftover
license: AGPL-3.0 license
website: 
  url: https://variantvalidator.org/
  source:
    type: github
    repo_slug: openvar/variantvalidator
  tools:
    Validator:
      description:
      - Validation of multiple sequence variant description formats
      inputs:
      - vcf
      - hgvs g. c. r. p.
      - other
      - RefSeq Data
      outputs:
      - vcf
      - hgvs g. c. r. g.
      - Gene information
      - links to UCSC genome browser, gnomAD, Varsome, RefSeq
      - liftover
      - RefSeq data
    GenesToTranscripts:
      description:
      - Shows available transcripts for a gene
      inputs:
      - HGNC:ID
      - gene symbol
      outputs:
      - gene symbol
      - gene id
      - available transcripts
      - annotation e.g. Mane Select
      - RefSeq data
    BatchValidator:
      description: 
      - VariantValidator functionality for multiple descriptions
      inputs:
      - see VariantValidator
      outputs:
      - see VariantValidator
api: 
  url: https://rest.variantvalidator.org/
  source:
    type: github
    repo_slug: openvar/rest_variantValidator
  tools:
    VariantValidator:
      description:
      - Validation of multiple sequence variant description formats
      inputs:
      - vcf
      - hgvs g. c. r. p.
      - other
      - Refseq Data
      outputs:
      - vcf
      - hgvs g. c. r. p.
      - gene information
      - lifover
      - Refseq data
    LOVD:
      description:
      - Genomic description to transcript and protein descriptions for use in pipelines.
      inputs:
      - vcf
      - hgvs g.
      outputs:
      - vcf
      - hgvs g. c. p.
      - gene information
      - liftover
      - RefSeq desctiptions
      - Ensembl descriptions
    gene2transcripts_v2:
      description:
      - Shows available transcripts for a gene, alignment data and information about each transcript
      inputs:
      - HGNC:ID
      - Gene symbol
      outputs:
      - gene id
      - gene symbol
      - transcript information
      - alignment data
      - Ensembl data
      - RefSeq data
    hgvs2reference:
    - Accepts a HGVS formatted description and returns the reference bases and alt bases
    inputs:
    - hgvs g. c.
    outputs:
    - reference bases
    - alt bases
    - normalized descriptions
    
description: |
  VariantValidator is a user-friendly software tool designed to validate the
  syntax and parameters of DNA variant descriptions according to the HGVS
  Sequence Variant Nomenclature.

  VariantValidator ensures that users are guided through the intricacies of the
  HGVS nomenclature, e.g. if the user makes a mistake, VariantValidator
  automatically corrects the mistake if it can, or provides helpful guidance if
  it cannot. In addition, VariantValidator accurately inter-converts between
  transcript variant descriptions and genomic variant descriptions in HGVS and
  Variant Call Format (VCF)

  VariantValidator interfaces with the hgvs package to parse, format, and
  manipulate biological sequence variants. See
  https://github.com/biocommons/hgvs/ for details of the hgvs package

  rest_VariantValidator and the Python libraries are highly functional platforms enabling high-throughput and
  embeddable utilisation of functionality of https://variantvalidator.org/

pubmed_id: "28967166"
```
